openapi: 3.0.3
info:
  title: ECMS
  description: ECMS API documents
  version: 1.0.0
  license:
    name: MIT
    url: https://github.com/betterde/ecms/blob/master/LICENSE
servers:
  - url: https://ecms.betterde.com
    description: Production server
  - url: https://ecms.it
    description: Develop server
tags:
  - name: Order
    description: Order API
  - name: User
    description: User API
paths:
  /user:
    get:
      tags:
        - User
      summary: Returns a list of users.
      description: Optional extended description in Markdown.
      responses:
        200:
          description: OK
  /order:
    get:
      tags:
        - Order
      summary: Returns a list of orders.
      description: Optional extended description in Markdown.
      parameters:
        - name: date
          in: query
          required: false
          description: Date string
      responses:
        '200':
          description: Success
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
security:
  - bearerAuth: []

